- name: Cambiar hostname según IP
  hosts: all
  become: yes

  vars:
    ip_hostname_map:
      "10.66.86.37": STO-CRIS

  tasks:

    - name: Obtener IP real
      set_fact:
        ip_actual: "{{ ansible_default_ipv4.address }}"

    - name: Debug IP
      debug:
        msg: "IP detectada: {{ ip_actual }}"

    - name: Obtener hostname correspondiente
      set_fact:
        nuevo_hostname: "{{ ip_hostname_map[ip_actual] }}"
      when: ip_actual in ip_hostname_map

    - name: Cambiar el hostname si corresponde
      hostname:
        name: "{{ nuevo_hostname }}"
      when: nuevo_hostname is defined

    - name: Confirmar cambio
      debug:
        msg: "Hostname cambiado a {{ nuevo_hostname }}"
      when: nuevo_hostname is defined