- name: Cambiar hostname simple
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Forzar hostname (método estable)
      copy:
        content: "STO-CRIS"
        dest: /etc/hostname

    - name: Aplicar hostname inmediato
      command: hostname STO-CRIS

    - name: Verificar hostname
      command: hostname
      register: resultado

    - name: Mostrar resultado
      debug:
        msg: "Hostname final: {{ resultado.stdout }}"
